// GENERATED by scripts/generate-wallpapers.mjs — do not edit by hand.
// Re-run it after changing any wallpaper composition.

export interface WallpaperDownloadFile {
  /** Human size label shown on the download chip, e.g. `5K`. */
  label: string;
  width: number;
  height: number;
  href: string;
  file: string;
  bytes: number;
}

export interface WallpaperDownload {
  /** `mark` = the brand wallpaper; `product` = a wallpaper you can set on a Zed home. */
  group: 'mark' | 'product';
  id: string;
  name: string;
  theme: 'light' | 'dark';
  /** Small JPEG of this exact composition, for the card on /design-system. */
  preview: string;
  files: WallpaperDownloadFile[];
}

export const WALLPAPER_DOWNLOADS: WallpaperDownload[] = [
  {
    group: 'mark',
    id: 'symbol',
    name: 'Symbol',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-symbol-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-symbol-light-5120x2880.png',
        file: 'zed-symbol-light-5120x2880.png',
        bytes: 55203,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/zed-symbol-light-3840x2160.png',
        file: 'zed-symbol-light-3840x2160.png',
        bytes: 33331,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/zed-symbol-light-2560x1440.png',
        file: 'zed-symbol-light-2560x1440.png',
        bytes: 16645,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-symbol-light-1290x2796.png',
        file: 'zed-symbol-light-1290x2796.png',
        bytes: 17506,
      },
    ],
  },
  {
    group: 'mark',
    id: 'logo',
    name: 'Logo',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-logo-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-logo-light-5120x2880.png',
        file: 'zed-logo-light-5120x2880.png',
        bytes: 56723,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/zed-logo-light-3840x2160.png',
        file: 'zed-logo-light-3840x2160.png',
        bytes: 34448,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/zed-logo-light-2560x1440.png',
        file: 'zed-logo-light-2560x1440.png',
        bytes: 17471,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-logo-light-1290x2796.png',
        file: 'zed-logo-light-1290x2796.png',
        bytes: 18709,
      },
    ],
  },
  {
    group: 'product',
    id: 'dither',
    name: 'Dither',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-dither-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-dither-light-5120x2880.png',
        file: 'zed-dither-light-5120x2880.png',
        bytes: 58385,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-dither-light-1290x2796.png',
        file: 'zed-dither-light-1290x2796.png',
        bytes: 18464,
      },
    ],
  },
  {
    group: 'product',
    id: 'brandmark',
    name: 'Brandmark',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-brandmark-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-brandmark-light-5120x2880.png',
        file: 'zed-brandmark-light-5120x2880.png',
        bytes: 183262,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-brandmark-light-1290x2796.png',
        file: 'zed-brandmark-light-1290x2796.png',
        bytes: 33268,
      },
    ],
  },
  {
    group: 'product',
    id: 'nebula',
    name: 'Pixel Beams',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-nebula-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-nebula-light-5120x2880.png',
        file: 'zed-nebula-light-5120x2880.png',
        bytes: 61487,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-nebula-light-1290x2796.png',
        file: 'zed-nebula-light-1290x2796.png',
        bytes: 17230,
      },
    ],
  },
  {
    group: 'product',
    id: 'silk',
    name: 'Silk',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-silk-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-silk-light-5120x2880.jpg',
        file: 'zed-silk-light-5120x2880.jpg',
        bytes: 144781,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-silk-light-1290x2796.jpg',
        file: 'zed-silk-light-1290x2796.jpg',
        bytes: 51628,
      },
    ],
  },
  {
    group: 'product',
    id: 'grain',
    name: 'Grain',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-grain-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-grain-light-5120x2880.jpg',
        file: 'zed-grain-light-5120x2880.jpg',
        bytes: 1107200,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-grain-light-1290x2796.jpg',
        file: 'zed-grain-light-1290x2796.jpg',
        bytes: 223309,
      },
    ],
  },
  {
    group: 'product',
    id: 'neuro',
    name: 'Neuro',
    theme: 'light',
    preview: '/wallpapers/downloads/zed-neuro-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-neuro-light-5120x2880.jpg',
        file: 'zed-neuro-light-5120x2880.jpg',
        bytes: 356668,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-neuro-light-1290x2796.jpg',
        file: 'zed-neuro-light-1290x2796.jpg',
        bytes: 88353,
      },
    ],
  },
  {
    group: 'mark',
    id: 'symbol',
    name: 'Symbol',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-symbol-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-symbol-dark-5120x2880.png',
        file: 'zed-symbol-dark-5120x2880.png',
        bytes: 54709,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/zed-symbol-dark-3840x2160.png',
        file: 'zed-symbol-dark-3840x2160.png',
        bytes: 32948,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/zed-symbol-dark-2560x1440.png',
        file: 'zed-symbol-dark-2560x1440.png',
        bytes: 16441,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-symbol-dark-1290x2796.png',
        file: 'zed-symbol-dark-1290x2796.png',
        bytes: 17400,
      },
    ],
  },
  {
    group: 'mark',
    id: 'logo',
    name: 'Logo',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-logo-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-logo-dark-5120x2880.png',
        file: 'zed-logo-dark-5120x2880.png',
        bytes: 55943,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/zed-logo-dark-3840x2160.png',
        file: 'zed-logo-dark-3840x2160.png',
        bytes: 33910,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/zed-logo-dark-2560x1440.png',
        file: 'zed-logo-dark-2560x1440.png',
        bytes: 17158,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-logo-dark-1290x2796.png',
        file: 'zed-logo-dark-1290x2796.png',
        bytes: 18422,
      },
    ],
  },
  {
    group: 'product',
    id: 'dither',
    name: 'Dither',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-dither-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-dither-dark-5120x2880.png',
        file: 'zed-dither-dark-5120x2880.png',
        bytes: 58313,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-dither-dark-1290x2796.png',
        file: 'zed-dither-dark-1290x2796.png',
        bytes: 18401,
      },
    ],
  },
  {
    group: 'product',
    id: 'brandmark',
    name: 'Brandmark',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-brandmark-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-brandmark-dark-5120x2880.png',
        file: 'zed-brandmark-dark-5120x2880.png',
        bytes: 181161,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-brandmark-dark-1290x2796.png',
        file: 'zed-brandmark-dark-1290x2796.png',
        bytes: 33167,
      },
    ],
  },
  {
    group: 'product',
    id: 'nebula',
    name: 'Pixel Beams',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-nebula-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-nebula-dark-5120x2880.png',
        file: 'zed-nebula-dark-5120x2880.png',
        bytes: 62826,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-nebula-dark-1290x2796.png',
        file: 'zed-nebula-dark-1290x2796.png',
        bytes: 17944,
      },
    ],
  },
  {
    group: 'product',
    id: 'silk',
    name: 'Silk',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-silk-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-silk-dark-5120x2880.jpg',
        file: 'zed-silk-dark-5120x2880.jpg',
        bytes: 162459,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-silk-dark-1290x2796.jpg',
        file: 'zed-silk-dark-1290x2796.jpg',
        bytes: 45115,
      },
    ],
  },
  {
    group: 'product',
    id: 'grain',
    name: 'Grain',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-grain-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-grain-dark-5120x2880.jpg',
        file: 'zed-grain-dark-5120x2880.jpg',
        bytes: 842820,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-grain-dark-1290x2796.jpg',
        file: 'zed-grain-dark-1290x2796.jpg',
        bytes: 168003,
      },
    ],
  },
  {
    group: 'product',
    id: 'neuro',
    name: 'Neuro',
    theme: 'dark',
    preview: '/wallpapers/downloads/zed-neuro-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/zed-neuro-dark-5120x2880.jpg',
        file: 'zed-neuro-dark-5120x2880.jpg',
        bytes: 414552,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/zed-neuro-dark-1290x2796.jpg',
        file: 'zed-neuro-dark-1290x2796.jpg',
        bytes: 102084,
      },
    ],
  },
];
